>Deinococcus_Radiodurans_R1 gene85
MPIALAGGGFFRVSAPPARTPYPEAMSYAEVLGMTILDASPDLTRVALTVTEAGLNMHGT
AHGGLIFSLADEAFAVISNLDAQAVAAETHMSFFRAAREGERLVAVATPERVGRTLATYR
IEVRR----GEEGEVLALFLGTVSRREKQS----
>Deinococcus_gobiensis_I0 gene85
-------------------------MSLDQTLGMRLLDHSPQRTRVTLTVGPDGVNMHGS
AHGGLIFSLADQAFAVISNLEVQAVAAETHLSFFRAAFPGDRLVAVATPERVGRTLATYR
VEVRRIRDEADEGELVALFLGTVSRRGAQPSSSG
