>Deinococcus_Radiodurans_R1 gene93
MGQTGSLGKKPGSSPRGTARESSQITNSALNNPKIAHRPRPCDRLVSRAVSGSLHPARSA
QALFLTVMTAYAASSSAAPATGGFYAERLSRPGAVLAPMAGYSDAPMRQLAAEQGALWTV
SEMISARGLVLGSEQESLSLGRPYPGEQGRAVQLFGADPDVLADAVGKAEAWFAPAAIDL
NLGCPVPKVRGKGGACLLQTPEVAYELVRAMRQATGLDVSAKIRLGWDENRSVEIAQGLE
AAGAAVVTVHGRTSAQRYTGNADWDAIGRVAQAVRIPVIGSGDVLSPVQARERMQQSGVA
AVMIGRGAVGNPWMFRAIASGEETLPPAQERARTALRHAELQHDFYTTPHRRDPSRLHVA
SMRPLRKVLPKYLPDQPDLHPALHQVETLDDVRAALVPLLAESLRS-------------
>Deinococcus_gobiensis_I0 gene93
------------------------------------------------------------
--------------------------------------MAGYSDAPMRQLAAEQGALWTV
SEMISARGLVLGGENESLNLGRPYPGEQGRVVQLFGADPEVLAEAVRRAEAWFSPAAIDL
NMGCPVPKVRGKGGACLLQTPEVAYDLVRAMRSATSLDVSAKIRLGWDSDRSLEVAQGLA
EAGAAVITVHGRTSAQRYTGEADWAAIARVAAAVPTPVIGSGDVLSPAQATERR-ALGVA
AVMIGRGAVGNPWIFRALAGGAPAVPDAATRAGTALRHAELQDTFYTAPDRHRPGELRRA
SMRPLRKVLPKYLPDLPELHPALLQAETLDDVRAALAPVLATRPAGPRGPAVGVAGSRA
