>Deinococcus_Radiodurans_R1 gene29
---------------------------------------------------------MKA
EGFLAGALDWRAKRLIRRSDGTVLGALQAQGMRTLWAAGYELLGPDDSVRFTIRNDQPWM
SVVEGAIDAVPLIGDFVAMGFDYFVNPTYTVSDPGGQPTYRVHKKRSFFSRRFVIEELRP
GPAENDELVLLGLIQLVLRERERG
>Deinococcus_gobiensis_I0 gene29
MNPQFPLSIEFRFSLFTELRVTDASGRLLAFVKEKTFSIRDEVRVYTDESRQVQTHGMRA
QGLMAGMLDWRARRVIVRADGTEVGSLQAQGMRTLWAAGYDLLGPGGQTRFTIRDDQPWM
SLVEAGIGAVPFVGDLVAMGFDYLVNPTYTVLDPAGAPAYRVHKKRSLLSRRFTVEELRP
TTPGDDELVLLGLVQLVLRERERG
