>Deinococcus_Radiodurans_R1 gene91
MRLRPTPFPLWRNCTPKASTARPKPLLLLAPLRFRPLARTQRGGVMKTAVIQFPGSNCDA
DALHAARLLLDDGAQFVWHTETALPEGTELVFLPGGFSYGDHLRSGAIAARSPIMNAVKA
HAEAGGYVLGVCNGFQVLTEAGLLPGALSRNKELHFMCKPVHLRVENNATDFSRAYGPGQ
IIEIPIAHGEGNYYADAATIAELEEGGRVVFRYAD-------NPNGSLNDIAGIVNERGN
VLGMMPHPERAVELLLGSEDGKGVFESLKTVKK-
>Thermus_thermophilus_HB8 gene91
---------------------------------------------MRWAIVRFPGANCDE
DARFALEK-AGIRAEFVWHTERDL-RGFDGVFLPGGFSYGDYLRAGALAAKSPVMEAVRR
FAEEGRYVVGVCNGFQILTEAGLLPGALLANLNLHFTCKEVGVRVERNDLPFTRLYPRGQ
VLRLPIAHGEGRYYADPETLARLEGEGLVVFRYAPLKDEADYNPNGSLHDIAGIVSEKGN
VLGMMPHPERAVDEVLGNTDGLPFFLGLVKEVAR
